settings:
  title: 'Status Page'
  url: 'https://cf-status.alterem.us.kg/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 15 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: chat-gpt-next-web # unique identifier
    name: chat-gpt-next-web
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://chat-gpt-next-web.alterem.us.kg' # URL to fetch
    method: GET # default=GET
    expectStatus: 403 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: jxchelian
    name: jxchelian
    url: 'https://jxchelian.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: opensearch-dashboard
    name: opensearch-dashboard
    url: 'https://opensearch-dashboard.vitality.us.kg'
    method: GET
    expectStatus: 401
    linkable: true
