settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: chat-gpt-next-web # unique identifier
    name: chat-gpt-next-web
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://chat-gpt-next-web.alterem.top' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: lobe-chat
    name: lobe-chat
    description: 'Built for anything connected to the Internet.'
    url: 'https://lobe-chat.alterem.top'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: docker-github
    name: docker-github
    description: 'docker-hub & github Accelerate.'
    url: 'https://docker-hub.vitality.us.kg'
    method: GET
    expectStatus: 200
    linkable: true

  - id: docker-hub
    name: docker-hub
    description: 'docker-hub Accelerate.'
    url: 'http://docker-hub.vitality.us.kg'
    method: GET
    expectStatus: 200
    linkable: true

  - id: cockpit
    name: cockpit
    url: 'https://cockpit.alterem.top/'
    method: GET
    expectStatus: 200
